version: 2
sources:
  - name: airbnb
    schema: raw
    tables:
    - name: listings
      identifier: raw_listings
    - name: hosts
      identifier: raw_host
    - name: reviews
      identifier: raw_review
